[package]
name = "synqueue"
description = "Internally synchronized (MPMC) queue"
license = "MIT"
homepage = "https://github.com/kvark/synqueue"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
loom = { version = "0.5", optional = true }
profiling = "1"